name: eds-geospatial
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - uv
  - just
  
  # Core Geospatial Stack 
  - geospatial          # Installs xarray, geopandas, rasterio, etc.
  
  # Climate Data Streaming 
  - intake
  - intake-esm
  - aiohttp             # Required for fast downloading
  - zarr                # Required for cloud-native data format

  # Satellite Data Streaming
  - pystac-client       # Generic search tool
  - stackstac           # Converts search results to datacubes
  - planetary-computer  # Microsoft authentication

  # GeoAI & Deep Learning
  - segment-geospatial  # SAMGeo
  
  - pip:
    - git+https://github.com/opengeos/geoai.git