name: eds-geospatial
channels:
  - conda-forge
dependencies:
  # NÃºcleo
  - python=3.10
  - pip
  - jupyterlab
  - ipykernel

  # Geoespacial (solo conda-forge)
  - gdal
  - geopandas
  - rasterio
  - pyproj
  - shapely
  - fiona
  - rtree            # spatial index
  - geotiff
  - proj
  - geos

  # OpenGeos stack moderno
  - leafmap
  - earthengine-api

  # Ciencia de datos
  - pandas
  - scikit-learn
  - matplotlib
  - numpy
