name: eds-geospatial
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - uv
  
  # Core Geospatial Stack 
  - geospatial          # Core bundle (geopandas, rasterio, etc.)
  
  # Interactive Mapping Additions
  - leafmap
  - ipyleaflet
  
  # Climate & Satellite Streaming (keep as-is)
  - intake
  - intake-esm
  - aiohttp
  - zarr
  - pystac-client
  - stackstac
  - planetary-computer

  # GeoAI
  - segment-geospatial
  
  - pip:
    - git+https://github.com/opengeos/geoai.git
