name: eds-geospatial
channels:
  - conda-forge
dependencies:
  # --- Core Python & Jupyter ---
  - python=3.10
  - pip
  - jupyterlab

  # --- Core Geospatial Stack ---
  
  - gdal
  - geopandas
  - rasterio
  - pyproj
  - shapely
  - fiona

  # --- Modern OpenGeos Stack ---
  - leafmap
  - earthengine-api
  - samgeo               
  - segment-anything-hq   
  
  # --- ML & Data Science ---
  - scikit-learn
  - pandas
  - matplotlib
  
  # --- Pip-only packages ---
  - pip:
    # geoai is a good geospatial resource to have.
    - "git+https://github.com/opengeos/geoai.git"